//AS3ExporterAIR version 2.3, code Flash 10, generated by Prefab3D: http://www.closier.nl/prefab
package tileset.wall
{
	import away3d.containers.ObjectContainer3D;
	import away3d.containers.Scene3D;
	import away3d.materials.*;
	import away3d.core.base.*;
	import away3d.loaders.utils.*;
	import away3d.loaders.data.*;
	import flash.utils.Dictionary;
	import away3d.primitives.*;
	import flash.display.Bitmap;
	import flash.display.BitmapData;

	import flash.geom.*;

	public class Wall extends Mesh
	{
		[Embed(source="images/aw_0.jpg")]
		private var Aw_0_Bitmap_Bitmap:Class;

		private var objs:Object = {};
		private var geos:Array = [];
		private var oList:Array =[];
		private var aC:Array;
		private var aV:Array;
		private var aU:Array;
		private var _scale:Number;

		public function Wall(scale:Number = 1)
		{
			_scale = scale;
			setSource();
			addContainers();
			buildMeshes();
			buildMaterials();
			cleanUp();
		}

		private function buildMeshes():void
		{
			var m0:Matrix3D = new Matrix3D();
			m0.rawData = Vector.<Number>([1,0,0,0,0,1,0,0,0,0,1,0,0*_scale,0*_scale,0*_scale,1]);
			transform = m0;

			objs.obj0 = {name:"aw_0",  transform:m0, pivotPoint:new Vector3D(0,0,0), container:-1, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj0.geo=geos[0];

			var ref:Object;
			
			var j:int;
			var av:Array;
			var au:Array;
			var v0:Vertex;
			var v1:Vertex;
			var v2:Vertex;
			var u0:UV;
			var u1:UV;
			var u2:UV;
			var aRef:Vector.<Face>;
			for(var i:int = 0;i<1;++i){
				ref = objs["obj"+i];
				if(ref != null){
					this.type = ".as";
					this.bothsides = ref.bothsides;
					this.name = ref.name;
					this.pushfront = ref.pushfront;
					this.pushback = ref.pushback;
					this.ownCanvas = ref.ownCanvas;

					oList.push(this);
					this.transform = ref.transform;
					this.movePivot(ref.pivotPoint.x, ref.pivotPoint.y, ref.pivotPoint.z);
					if (ref.geo.geometry != null) {
						this.geometry = ref.geo.geometry;
						continue;
					}
					ref.geo.geometry = new Geometry();
					this.geometry = ref.geo.geometry;
					aRef = ref.geo.f;
					for(j = 0;j<aRef.length;++j){
						Face(aRef[j]).material = ref.material;
						ref.geo.geometry.addFace( Face(aRef[j]));
					}

				}
			}
		}

		private function setSource():void
		{
			var geo0vert:String ="1f4.0000000000001/190/-1f3.5af3107a3fde,-4.34e2d209aa05ce-1d/1f4/2.c87e98752c09e-d,1f3.9184e729fff/190/1f4.0000000000001,-18f.5af3107a3ffa/-63.5af3107a3ffd/-12b.5af3107a3ffa,-1f3.9184e729fff/-63.5af3107a3ffd/-1f3.9184e729fff,-1f3.9184e729fff/-1f4/-1f3.9184e729fff,-1f4.0000000000001/-1f4/1f3.9184e729fff,-c8.00000000000006/-1f4/c8.0000000000001,1f3.9184e729fff/-1f4/1f4.0000000000001,1f4.0000000000001/-1f4/-1f3.5af3107a3fde,5.35e2364b51525e-e/-1f4/-10b.4f378c8f57e7,12b.5af3107a3ffa/-1f4/c8.00000000000017,-1e4.32b/-1f4/1.51d36446832c5e-d,-1e4.22a6d8f74803/-63.5af3107a3ffd/1.83ca21aab66de-d,-c8.00000000000006/1f4/12c,-1f4.0000000000001/-63.5af3107a3ffd/1f3.9184e729fff,-1d9.b8/-c8/c8.00000000000006,-1f4.0000000000001/190/1f3.9184e729fff,-18f.5af3107a3ffa/c7.5af3107a3ffa/-c8.00000000000003,-1f3.9184e729fff/190/-1f3.9184e729fff,-190.00000000000006/12c.00000000000006/12b.5af3107a3ffa,-190/12c.00000000000006/-63.5af3107a3ffc";
			var geo0uvs:String ="0.532bb/0.517bc,0.3000e/0.2d63a,0.0bece/0.517bc,0.413d8/0.79bcd,0.4e1c9/0.79449,0.4e1ca/0.5dbe4,0.59c87/0.514f1,0.6ff15/0.3bfa2,0.59c87/0.0a30b,0.a0e6d/0.0a30b,0.e647/0.2d468,0.a0e6d/0.514f1,0.6f026/0.1968d,0.7e4e5/0.4f4d7,0.2cb80/0.78e3f,0.1a692/0.1f7a5,0.0b098/0.78a8e,0.1f118/0.72688,0.478e/0.5dbe4,0.0b098/0.5dbe4,0.0b098/0.9a7c6,0.3abd7/0.8d886,0.4e1c9/0.9b28e,0.19047/0.94d5a,0.0bece/0.010fd,0.34119/0.17bd,0.532bb/0.0b2c2,0.37de1/0.0d89f,0.1b999/0.0b8d7";
			var geo0faces:String ="0,1,2,0,1,2,3,4,5,3,4,5,6,7,8,6,7,8,9,a,5,9,a,b,8,b,9,8,c,9,6,c,7,6,d,7,a,b,7,a,c,7,c,a,7,d,a,7,d,3,5,e,3,5,1,e,2,1,f,2,f,10,c,10,11,12,6,f,c,13,10,12,10,f,11,11,10,14,d,12,3,e,15,3,13,4,3,16,4,3,12,13,3,15,16,3,d,5,c,e,5,12,10,d,c,11,e,12,11,14,d,14,17,e,10,11,d,11,14,e,2,e,11,2,f,18,15,12,d,19,15,e,14,15,d,17,19,e,12,15,13,15,19,16,13,1,0,1a,1,0,13,15,1,1a,1b,1,e,14,11,f,1c,18,b,a,9,c,a,9,7,b,8,7,c,8,a,c,5,a,d,b,e,1,15,f,1,1b,14,e,15,1c,f,1b";
			var geo0:FacesDefinition = new FacesDefinition();
			geo0.f = buildFaces( geo0faces.split(","),  buildVertices(read(geo0vert).split(",")), buildUVs(read(geo0uvs).split(",")) );
			geos.push(geo0);
		}

		private function buildFaces(aFaces:Array, vVerts:Vector.<Vertex>, vUVs:Vector.<UV>):Vector.<Face>
		{
			var vFaces:Vector.<Face> = new Vector.<Face>();
			var f:Face;
			for(var i:int = 0;i<aFaces.length;i+=6){
				f = new Face( vVerts[parseInt(aFaces[i], 16)],
									vVerts[parseInt(aFaces[i+1], 16)],
									vVerts[parseInt(aFaces[i+2], 16)],
									null,
									vUVs[parseInt(aFaces[i+3], 16)],
									vUVs[parseInt(aFaces[i+4], 16)],
									vUVs[parseInt(aFaces[i+5], 16)]);
				vFaces.push(f);
			}

			return vFaces;
		}

		private function buildVertices(aVerts:Array):Vector.<Vertex>
		{
			var tmpv:Array;
			var vVerts:Vector.<Vertex> = new Vector.<Vertex>();
			for(var i:int = 0;i<aVerts.length;i++){
				tmpv = aVerts[i].split("/");
				vVerts[i] = new Vertex( parseFloat(tmpv[0])*_scale, parseFloat(tmpv[1])*_scale, parseFloat(tmpv[2])*_scale  );
			}
			return vVerts;
		}

		private function buildUVs(aUvs:Array):Vector.<UV>
		{
			var tmpv:Array;
			var vUVs:Vector.<UV> = new Vector.<UV>();
			for(var i:int = 0;i<aUvs.length;++i){
				tmpv = aUvs[i].split("/");
				vUVs[i] = new UV(parseFloat(tmpv[0]), parseFloat(tmpv[1]));
			}

			return vUVs;
		}


		private function buildMaterials():void
		{
				var aw_0_Bitmap:Bitmap = new Aw_0_Bitmap_Bitmap();
				applyMaterialToMesh("aw_0", aw_0_Bitmap.bitmapData);

		}

		private function applyMaterialToMesh(id:String, bmd:BitmapData):void
		{
			for(var i:int;i<meshes.length;++i){
				if(meshes[i].name == id){
					if(!bmd){
						trace("Embed of "+id+" failed! Check source path or if CS4 call 911!");
					} else {
					meshes[i].material = new BitmapMaterial(bmd);
					}
					break;
				}
			}
		}

		private function cleanUp():void
		{
			for(var i:int = 0;i<1;++i){
				objs["obj"+i] == null;
			}
			aV = null;
			aU = null;
		}

		private function addContainers():void
		{}


		public function get meshes():Array
		{
			return oList;
		}


		private function read(str:String):String
		{
			var start:int= 0;
			var chunk:String;
			var end:int= 0;
			var dec:String = "";
			var charcount:int = str.length;
			for(var i:int = 0;i<charcount;++i){
				if (str.charCodeAt(i)>=44 && str.charCodeAt(i)<= 48 ){
					dec+= str.substring(i, i+1);
				}else{
					start = i;
					chunk = "";
					while(str.charCodeAt(i)!=44 && str.charCodeAt(i)!= 45 && str.charCodeAt(i)!= 46 && str.charCodeAt(i)!= 47 && i<=charcount){
						i++;
					}
					chunk = ""+parseInt("0x"+str.substring(start, i), 16 );
					dec+= chunk;
					i--;
				}
			}
			return dec;
		}

	}
}
class FacesDefinition
{
	import away3d.core.base.Face;
	import away3d.core.base.Geometry;
	public var f:Vector.<Face>;
	public var geometry:Geometry;
}