//AS3ExporterAIR version 2.3, code Flash 10, generated by Prefab3D: http://www.closier.nl/prefab
package tileset.box
{
	import away3d.containers.ObjectContainer3D;
	import away3d.containers.Scene3D;
	import away3d.materials.*;
	import away3d.core.base.*;
	import away3d.loaders.utils.*;
	import away3d.loaders.data.*;
	import flash.utils.Dictionary;
	import away3d.primitives.*;
	import flash.display.Bitmap;
	import flash.display.BitmapData;

	import flash.geom.*;

	public class Box extends Mesh
	{
		[Embed(source="images/aw_0.jpg")]
		private var Aw_0_Bitmap_Bitmap:Class;

		private var objs:Object = {};
		private var geos:Array = [];
		private var oList:Array =[];
		private var aC:Array;
		private var aV:Array;
		private var aU:Array;
		private var _scale:Number;

		public function Box(scale:Number = 1)
		{
			_scale = scale;
			setSource();
			addContainers();
			buildMeshes();
			buildMaterials();
			cleanUp();
		}

		private function buildMeshes():void
		{
			var m0:Matrix3D = new Matrix3D();
			m0.rawData = Vector.<Number>([1,0,0,0,0,1,0,0,0,0,1,0,0*_scale,500*_scale,0*_scale,1]);
			transform = m0;

			objs.obj0 = {name:"aw_0",  transform:m0, pivotPoint:new Vector3D(0,0,0), container:-1, bothsides:false, material:null, ownCanvas:false, pushfront:false, pushback:false};
			objs.obj0.geo=geos[0];

			var ref:Object;
			
			var j:int;
			var av:Array;
			var au:Array;
			var v0:Vertex;
			var v1:Vertex;
			var v2:Vertex;
			var u0:UV;
			var u1:UV;
			var u2:UV;
			var aRef:Vector.<Face>;
			for(var i:int = 0;i<1;++i){
				ref = objs["obj"+i];
				if(ref != null){
					this.type = ".as";
					this.bothsides = ref.bothsides;
					this.name = ref.name;
					this.pushfront = ref.pushfront;
					this.pushback = ref.pushback;
					this.ownCanvas = ref.ownCanvas;

					oList.push(this);
					this.transform = ref.transform;
					this.movePivot(ref.pivotPoint.x, ref.pivotPoint.y, ref.pivotPoint.z);
					if (ref.geo.geometry != null) {
						this.geometry = ref.geo.geometry;
						continue;
					}
					ref.geo.geometry = new Geometry();
					this.geometry = ref.geo.geometry;
					aRef = ref.geo.f;
					for(j = 0;j<aRef.length;++j){
						Face(aRef[j]).material = ref.material;
						ref.geo.geometry.addFace( Face(aRef[j]));
					}

				}
			}
		}

		private function setSource():void
		{
			var geo0vert:String ="-1f4/-1f4/-1f4,-1f4/-63.5af3107a3ffd/-1f4,0/-63.5af3107a3ffd/-1c1.2d6,-1f4/190/-1f4,1f4/190/1f4,0/-63.5af3107a3ffd/1c1.2d6,1f4/-63.5af3107a3ffd/1f4,1f4/-1f4/1f4,-12c/-1f4/12c,-12c/-1f4/-12c,12c/-1f4/-12c,12c/-1f4/12c,-1f4/-1f4/1f4,-1f4/-63.5af3107a3ffd/1f4,-1c1.2d6/-63.5af3107a3ffd/0,-1f4/190/1f4,1f4/-1f4/-1f4,1f4/-63.5af3107a3ffd/-1f4,1c1.2d6/-63.5af3107a3ffd/0,1f4/190/-1f4,-12c/1f4/-12c,-12c/1f4/12c,12c/1f4/12c,12c/1f4/-12c";
			var geo0uvs:String ="0.57fb/0.2ebcf,0.48b99/0.2edf2,0.7598/0.18912,0.5f22c/0.2ec7d,0.5ef28/0.86de2,0.499d3/0.70eb4,0.48ee6/0.86eb3,0.37517/0.86f5b,0.013b98/0.25d12,0.2e2a6/0.25ca9,0.2e23c/0.01229,0.013b2e/0.0b604,0.37377/0.5af6d,0.48d44/0.5aec3,0.4982d/0.44e53,0.5ed87/0.5adef,0.3767b/0.b3072,0.49085/0.b2fcb,0.49b73/0.9cf38,0.5f112/0.11e4c,0.36f1d/0.00262d,0.01167/0.02923,0.0aeb6/0.2ea3b,0.68509/0.25915,0.81d3f/0.259ee,0.81ea7/0.0bf78,0.68679/0.0bd14,0.8af17/0.2ed62,0.8b17e/0.02d2c,0.5f4a7/0.02883,0.48caa/0.002452";
			var geo0faces:String ="0,1,2,0,1,2,2,1,3,2,1,3,4,5,6,4,5,6,6,5,7,6,5,7,8,9,a,8,9,a,b,8,a,b,8,a,c,d,e,c,d,e,e,d,f,e,d,f,10,11,12,10,11,12,12,11,13,12,11,13,9,0,10,9,0,14,a,9,10,a,9,14,a,10,7,a,14,15,b,a,7,b,a,15,b,7,c,b,15,16,8,b,c,8,b,16,8,c,0,8,16,0,9,8,0,9,8,0,14,15,16,17,18,19,17,14,16,1a,17,19,15,f,4,18,1b,1c,16,15,4,19,18,1c,16,4,13,19,1c,1d,17,16,13,1a,19,1d,14,3,f,17,3,1b,15,14,f,18,17,1b,5,c,7,5,c,7,4,f,5,4,f,5,f,d,5,f,d,5,5,d,c,5,d,c,3,e,f,3,e,f,0,e,1,0,e,1,3,1,e,3,1,e,0,c,e,0,c,e,13,2,3,1d,2,3,10,2,11,14,2,1e,13,11,2,1d,1e,2,10,0,2,14,0,2,7,10,12,7,10,12,4,12,13,4,12,13,4,6,12,4,6,12,7,12,6,7,12,6,17,13,3,1a,1d,3,14,17,3,17,1a,3";
			var geo0:FacesDefinition = new FacesDefinition();
			geo0.f = buildFaces( geo0faces.split(","),  buildVertices(read(geo0vert).split(",")), buildUVs(read(geo0uvs).split(",")) );
			geos.push(geo0);
		}

		private function buildFaces(aFaces:Array, vVerts:Vector.<Vertex>, vUVs:Vector.<UV>):Vector.<Face>
		{
			var vFaces:Vector.<Face> = new Vector.<Face>();
			var f:Face;
			for(var i:int = 0;i<aFaces.length;i+=6){
				f = new Face( vVerts[parseInt(aFaces[i], 16)],
									vVerts[parseInt(aFaces[i+1], 16)],
									vVerts[parseInt(aFaces[i+2], 16)],
									null,
									vUVs[parseInt(aFaces[i+3], 16)],
									vUVs[parseInt(aFaces[i+4], 16)],
									vUVs[parseInt(aFaces[i+5], 16)]);
				vFaces.push(f);
			}

			return vFaces;
		}

		private function buildVertices(aVerts:Array):Vector.<Vertex>
		{
			var tmpv:Array;
			var vVerts:Vector.<Vertex> = new Vector.<Vertex>();
			for(var i:int = 0;i<aVerts.length;i++){
				tmpv = aVerts[i].split("/");
				vVerts[i] = new Vertex( parseFloat(tmpv[0])*_scale, parseFloat(tmpv[1])*_scale, parseFloat(tmpv[2])*_scale  );
			}
			return vVerts;
		}

		private function buildUVs(aUvs:Array):Vector.<UV>
		{
			var tmpv:Array;
			var vUVs:Vector.<UV> = new Vector.<UV>();
			for(var i:int = 0;i<aUvs.length;++i){
				tmpv = aUvs[i].split("/");
				vUVs[i] = new UV(parseFloat(tmpv[0]), parseFloat(tmpv[1]));
			}

			return vUVs;
		}


		private function buildMaterials():void
		{
				var aw_0_Bitmap:Bitmap = new Aw_0_Bitmap_Bitmap();
				applyMaterialToMesh("aw_0", aw_0_Bitmap.bitmapData);

		}

		private function applyMaterialToMesh(id:String, bmd:BitmapData):void
		{
			for(var i:int;i<meshes.length;++i){
				if(meshes[i].name == id){
					if(!bmd){
						trace("Embed of "+id+" failed! Check source path or if CS4 call 911!");
					} else {
					meshes[i].material = new BitmapMaterial(bmd);
					}
					break;
				}
			}
		}

		private function cleanUp():void
		{
			for(var i:int = 0;i<1;++i){
				objs["obj"+i] == null;
			}
			aV = null;
			aU = null;
		}

		private function addContainers():void
		{}


		public function get meshes():Array
		{
			return oList;
		}


		private function read(str:String):String
		{
			var start:int= 0;
			var chunk:String;
			var end:int= 0;
			var dec:String = "";
			var charcount:int = str.length;
			for(var i:int = 0;i<charcount;++i){
				if (str.charCodeAt(i)>=44 && str.charCodeAt(i)<= 48 ){
					dec+= str.substring(i, i+1);
				}else{
					start = i;
					chunk = "";
					while(str.charCodeAt(i)!=44 && str.charCodeAt(i)!= 45 && str.charCodeAt(i)!= 46 && str.charCodeAt(i)!= 47 && i<=charcount){
						i++;
					}
					chunk = ""+parseInt("0x"+str.substring(start, i), 16 );
					dec+= chunk;
					i--;
				}
			}
			return dec;
		}

	}
}
class FacesDefinition
{
	import away3d.core.base.Face;
	import away3d.core.base.Geometry;
	public var f:Vector.<Face>;
	public var geometry:Geometry;
}